/* file generated by gen_js_enums.py */
'use strict';

var enums = {
  "EventType": {
    "ICE_CONNECTION_STATE_CONNECTED": 3, 
    "ROOM_SIZE_2": 2
  }, 
  "RequestField": {
    "MessageType": {
      "EVENT": "event"
    }, 
    "CLIENT_TYPE": "client_type", 
    "EventField": {
      "EVENT_TIME_MS": "event_time_ms", 
      "ROOM_ID": "room_id", 
      "EVENT_TYPE": "event_type", 
      "FLOW_ID": "flow_id"
    }, 
    "TYPE": "type", 
    "EVENT": "event", 
    "REQUEST_TIME_MS": "request_time_ms"
  }, 
  "ClientType": {
    "UNKNOWN": 0, 
    "ANDROID": 4, 
    "DESKTOP": 2, 
    "IOS": 3, 
    "JS": 1
  }
};
