runtime: go120
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: _go_app
  secure: always

env_variables:
  BYPASS_JOIN_CONFIRMATION: false
  # Comma-separated list of ICE urls to return when no ice server
  # is specified.
  ICE_SERVERS: ""
  # A message that is always displayed on the app page.
  # This is useful for cases like indicating to the user that this
  # is a demo deployment of the app.
  HEADER_MESSAGE: ""
  # Externel collider
  WSS_HOST: ""