service: goapprtc
runtime: go116
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  secure: always

env_variables:
  BYPASS_JOIN_CONFIRMATION: false
  # Only change these while developing, do not commit to source!
  # Use appcfg.py --env_variable=ICE_SERVER_API_KEY:KEY \
  # in order to replace variables when deploying.
  ICE_SERVER_API_KEY: ""
  # Comma-separated list of ICE urls to return when no ice server
  # is specified.
  ICE_SERVER_URLS: ""
  # A message that is always displayed on the app page.
  # This is useful for cases like indicating to the user that this
  # is a demo deployment of the app.
  HEADER_MESSAGE: ""