services:
  - type: web
    name: goapprtc
    region: ohio 
    plan: free
    env: go
    repo: https://github.com/dgv/goapprtc
    branch: master
    buildCommand: go build -tags netgo -ldflags '-s -w' -o goapprtc
    startCommand: ./goapprtc